evennia/web/urls.py
#
# File that determines what each URL points to. This uses _Python_ regular
# expressions, not Perl's.
#
# See:
# http://diveintopython.org/regular_expressions/street_addresses.html#re.matching.2.3
#

from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

## fix to resolve lazy-loading bug
## https://code.djangoproject.com/ticket/10405#comment:11
#from django.db.models.loading import cache as model_cache
#if not model_cache.loaded:
#    model_cache.get_models()

# loop over all settings.INSTALLED_APPS and execute code in
# files named admin.py in each such app (this will add those
# models to the admin site)
admin.autodiscover()

# Setup the root url tree from /

urlpatterns = [
    # User Authentication
    url(r'^accounts/login',  'django.contrib.auth.views.login', name="login"),
    url(r'^accounts/logout', 'django.contrib.auth.views.logout', name="logout"),

    # Page place-holder for things that aren't implemented yet.
    url(r'^tbi/', 'evennia.web.views.to_be_implemented', name='to_be_implemented'),

    # Admin interface
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # favicon
    url(r'^favicon\.ico$',  RedirectView.as_view(url='/media/images/favicon.ico')),

    # ajax stuff
    url(r'^webclient/', include('evennia.web.webclient.urls', namespace='webclient', app_name='webclient')),

    # Front page
    url(r'^$', 'evennia.web.views.page_index', name="index"),

    # Django original admin page. Make this URL is always available, whether
    # we've chosen to use Evennia's custom admin or not.
    url(r'django_admin/', 'evennia.web.views.admin_wrapper', name="django_admin")]

if settings.EVENNIA_ADMIN:
    urlpatterns += [
        # Our override for the admin.
        url('^admin/$', 'evennia.web.views.evennia_admin', name="evennia_admin"),

        # Makes sure that other admin pages get loaded.
        url(r'^admin/', include(admin.site.urls))]
else:
    # Just include the normal Django admin.
    urlpatterns += [url(r'^admin/', include(admin.site.urls))]

# This sets up the server if the user want to run the Django
# test server (this should normally not be needed).
if settings.SERVE_MEDIA:
    urlpatterns.extend([
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT})
    ])

evennia/web/webclient/urls.py
"""
This structures the (simple) structure of the
webpage 'application'.
"""
from django.conf.urls import *

urlpatterns = [
   url(r'^$', 'evennia.web.webclient.views.webclient', name="index")]

evennia/web/webclient/models.py
#
# Define database entities for the app. 
#

from django.db import models

evennia/web/views.py
"""
This file contains the generic, assorted views that don't fall under one of
the other applications. Views are django's way of processing e.g. html
templates on the fly.

"""
from django.contrib.admin.sites import site
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render

from evennia import SESSION_HANDLER
from evennia.objects.models import ObjectDB
from evennia.players.models import PlayerDB

_BASE_CHAR_TYPECLASS = settings.BASE_CHARACTER_TYPECLASS


def page_index(request):
    """
    Main root page.
    """
    # Some misc. configurable stuff.
    # TODO: Move this to either SQL or settings.py based configuration.
    fpage_player_limit = 4

    # A QuerySet of the most recently connected players.
    recent_users = PlayerDB.objects.get_recently_connected_players()[:fpage_player_limit]
    nplyrs_conn_recent = len(recent_users) or "none"
    nplyrs = PlayerDB.objects.num_total_players() or "none"
    nplyrs_reg_recent = len(PlayerDB.objects.get_recently_created_players()) or "none"
    nsess = SESSION_HANDLER.player_count()
    # nsess = len(PlayerDB.objects.get_connected_players()) or "no one"

    nobjs = ObjectDB.objects.all().count()
    nrooms = ObjectDB.objects.filter(db_location__isnull=True).exclude(db_typeclass_path=_BASE_CHAR_TYPECLASS).count()
    nexits = ObjectDB.objects.filter(db_location__isnull=False, db_destination__isnull=False).count()
    nchars = ObjectDB.objects.filter(db_typeclass_path=_BASE_CHAR_TYPECLASS).count()
    nothers = nobjs - nrooms - nchars - nexits

    pagevars = {
        "page_title": "Front Page",
        "players_connected_recent": recent_users,
        "num_players_connected": nsess or "no one",
        "num_players_registered": nplyrs or "no",
        "num_players_connected_recent": nplyrs_conn_recent or "no",
        "num_players_registered_recent": nplyrs_reg_recent or "no one",
        "num_rooms": nrooms or "none",
        "num_exits": nexits or "no",
        "num_objects": nobjs or "none",
        "num_characters": nchars or "no",
        "num_others": nothers or "no"
    }

    return render(request, 'evennia_general/index.html', pagevars)


def to_be_implemented(request):
    """
    A notice letting the user know that this particular feature hasn't been
    implemented yet.
    """

    pagevars = {
        "page_title": "To Be Implemented...",
    }

    return render(request, 'evennia_general/tbi.html', pagevars)


@staff_member_required
def evennia_admin(request):
    """
    Helpful Evennia-specific admin page.
    """
    return render(
        request, 'evennia_general/evennia_admin.html', {
            'playerdb': PlayerDB})


def admin_wrapper(request):
    """
    Wrapper that allows us to properly use the base Django admin site, if needed.
    """
    return staff_member_required(site.index)(request)

evennia/web/webclient/views.py
"""
This contains a simple view for rendering the webclient
page and serve it eventual static content.

"""
from django.shortcuts import render

from evennia.players.models import PlayerDB


def webclient(request):
    """
    Webclient page template loading.
    """

    # analyze request to find which port we are on
    if int(request.META["SERVER_PORT"]) == 8000:
        # we relay webclient to the portal port
        print "Called from port 8000!"
        #return redirect("http://localhost:8001/webclient/", permanent=True)

    nsess = len(PlayerDB.objects.get_connected_players()) or "none"
    # as an example we send the number of connected players to the template
    pagevars = {'num_players_connected': nsess}

    return render(request, 'webclient.html', pagevars)

evennia/web/templates/evennia_general/evennia_admin.html
{% extends "base.html" %}
{% block content %}
    <h1>Admin</h1>
    Welcome to the Evennia Admin Page. Here, you can edit many facets of players, characters, and other parts of the game.

    <h2><a href="{% url "admin:players_playerdb_changelist" %}">Players</a></h2>
    Players are user accounts. Players can have several characters under them. A user's login and password information can be changed here.

    <h2><a href="{% url "admin:objects_objectdb_changelist" %}">Objects</a></h2>
    Objects include everything from characters to rooms to exits.

    <h2><a href="{% url "admin:scripts_scriptdb_changelist" %}">Scripts</a></h2>
    Scripts are meta objects used to store game information, handle special functionality or perform timed actions.

    <h2><a href="{% url "admin:comms_channeldb_changelist" %}">Channels</a></h2>
    Channels are used for player communications.

    <h2><a href="{% url "admin:help_helpentry_changelist" %}">Help Topics</a></h2>

    <p>If you are an advanced user who needs access to the raw Django Admin, it is available <a href="{% url "django_admin" %}">here</a>.
        You can make this the default my changing <code>EVENNIA_ADMIN</code> to <code>False</code> in <code>settings.py</code> and reload.</p>
{% endblock content %}

evennia/web/templates/evennia_general/index.html
{% extends "base.html" %}

{% block sidebar %}
{% endblock %}

{% block header_ext %}
{% endblock %}

{% block content %}
<div class="rowOfBoxes">
   <!--div class="twoThirds noBorderOnLeft"-->
   <div class="noBorderOnLeft">
      <h1>Welcome!</h1>
      <p>Welcome to your new installation of <a href="http://evennia.com">Evennia</a>, your friendly
      neighborhood next-generation MUD development system and server. You are looking at Evennia's web
      presence, which can be expanded to a full-fledged site as
      needed. Through the <a href="{% url 'admin:index' %}">admin interface</a> you can view and edit the
      database without logging into the game.
        {% if webclient_enabled %}
        You can also connect to the game directly from your browser using our
        <a href="{% url 'webclient:index' %}">online client</a>!<br></br>
        {% endif %}
      For more info, take your time to
      peruse our extensive online <a href="https://github.com/evennia/evennia/wiki">documentation</a>.
      <p>
      Should you have any questions, concerns, bug reports, or
      if you want to help out, don't hesitate to join the Evennia community to make your voice heard! Drop a mail to the
      <a href="https://groups.google.com/forum/#!forum/evennia">mailing list</a> or to come say hi in the <a href="http://webchat.freenode.net/?channels=evennia">developer chatroom</a>. If you find bugs, please report them to our <a href="https://github.com/evennia/evennia/issues">Issue tracker</a>.
      </p>
   </div>
</div>

<div class="rowOfBoxes dividingBorderAbove">

   <div class="quarter noBorderOnLeft">
      <h1>Players</h1>
      <p>
      There's currently <strong>{{num_players_connected}}</strong> connected out of a total of <strong>{{num_players_registered}}</strong> players registered. Of these, <strong>{{num_players_registered_recent}}</strong> were created this week, and <strong>{{num_players_connected_recent}}</strong> have connected within the last seven days.
      </p>
   </div>

   <div class="quarter">
      <h1>Recently Connected</h1>
      <ul>
      {% for player in players_connected_recent %}
      <li>{{player.username}} -- <em>{{player.last_login|timesince}} ago</em></li>
      {% endfor %}
      </ul>
      <p class="filler"><!-- Filler para to extend left vertical line --></p>
   </div>

   <div class="quarter">
      <h1>Database Stats</h1>
      <ul>
      <li>{{num_players_registered}} players (+ {{num_characters}} characters)</li>
      <li>{{num_rooms}} rooms (+ {{num_exits}} exits)</li>
      <li>{{num_others}} other objects</li>

      </ul>
   </div>

   <div class="quarter">
      <h1>Evennia</h1>
      <p><a href="http://evennia.com">Evennia</a> is an open-source MUD server built in
      <a href="http://python.org">Python</a>, on top of the
      <a href="http://twistedmatrix.com">Twisted</a> and
      <a href="http://djangoproject.com">Django</a> frameworks. This
      combination of technologies allows for the quick and easy creation
      of the game of your dreams - as simple or as complex as you like.</p>
   </div>

</div>
{% endblock %}

evennia/web/templates/evennia_general/tbi.html
{% extends "base.html" %}

{% block header_ext %}
{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
<h1 id="alt-layout">To Be Implemented...</h1>
    <p>
      This feature has yet to be implemented, but rest assured that it will be!
      <br />
      <br />
      <br />
      Eventually...
    </p>
{% endblock %}

evennia/web/templates/prosimii/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-AU">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="author" content="haran" />
    <meta name="generator" content="haran" />

    {% if sidebar %}
    <link rel="stylesheet" type="text/css" href="{% static "evennia_general/css/prosimii-screen-alt.css" %}" media="screen" title="Prosimii (Sidebar)" />
    {% else %}
    <link rel="stylesheet" type="text/css" href="{% static "evennia_general/css/prosimii-screen.css" %}" media="screen" title="Prosimii" />
    {% endif %}
    <link rel="stylesheet alternative" type="text/css" href="{% static "evennia_general/css/prosimii-print.css" %}" media="screen" title="Print Preview" />
    <link rel="stylesheet" type="text/css" href="{% static "evennia_general/css/prosimii-print.css" %}" media="print" />

    {% block header_ext %}
    {% endblock %}

    <title>{{game_name}} - {% if flatpage %}{{flatpage.title}}{% else %}{% block titleblock %}{{page_title}}{% endblock %}{% endif %}</title>
  </head>

  <body>
    <!-- For non-visual user agents: -->
      <div id="top"><a href="#main-copy" class="doNotDisplay doNotPrint">Skip to main content.</a></div>

    <!-- ##### Header ##### -->

    <div id="header">
      <div class="superHeader">
        <!--span>Sites:</span-->
        <a href="http://evennia.com" title="The Python-based MUD server">Evennia.com</a>
      </div>

      <div class="midHeader">
        <img src="{% static "evennia_general/images/evennia_logo.png" %}" align='left'/> <h1 class="headerTitle" lang="la">{{game_name}}</h1>
        <div class="headerSubTitle" title="Slogan">
        <!-- Insert a slogan here if you want -->
        {{game_slogan}}			&nbsp;
        </div>

        <br class="doNotDisplay doNotPrint" />

        <div class="headerLinks">
          <span class="doNotDisplay">Tools:</span>
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Log Out &laquo;</a>
            <span class="doNotDisplay">|</span>
            Logged in as {{user.username}} &laquo;
          {% else %}
            <a href="{% url 'login' %}">Log In &laquo;</a>
            <span class="doNotDisplay">|</span>
            <a href="{% url 'to_be_implemented' %}">Register &laquo;</a>
          {% endif %}
        </div>
      </div>

      <div class="subHeader">
        <!--span class="doNotDisplay">Navigation:</span-->
        <a href="/">Home</a> |
        <a href="https://github.com/evennia/evennia/wiki/Evennia-Introduction/">About</a> |
        <a href="https://github.com/evennia/evennia/wiki">Documentation</a> |
        <a href="{% url 'admin:index' %}">Admin Interface</a>
        {% if webclient_enabled %}
         | <a href="{% url 'webclient:index' %}">Play Online</a>
        {% endif %}
        
      </div>
    </div>

    <!-- ##### Side Menu ##### -->
    {% block sidebar %}{% endblock %}
    <!-- ##### Main Copy ##### -->

    <div id="main-copy">
      {% block content %}
      {% endblock %}
    </div>

    <!-- ##### Footer ##### -->

    <div id="footer">
      <span class="doNotPrint">
        Template design by 
        <a href="http://www.oswd.org/designs/search/designer/id/3013/"
        title="Other designs by haran">haran</a>. 
        Powered by  
        <a href="http://evennia.com">Evennia.</a>
        <br />
      </span>
    </div>
  </body>
</html>